fix error in developer.vue
VueTubeApp/VueTube pull request #526
Opened 2022-08-28 21:01 UTC by tired6488

2022-08-28 21:12 UTC, gayolGate commented
thanks, it was my fault

2022-08-28 22:31 UTC, PickleNik requested changes

2022-08-28 22:31 UTC, PickleNik commented on NUXT/pages/mods/developer.vue
> +            label="lang.value"
```diff
- label="lang.value"
+ :label="lang.value"

2022-08-28 22:31 UTC, PickleNik commented on NUXT/pages/mods/developer.vue
> +          <v-text-field v-model="selectedKey" label="lang.key" solo />
```diff
- label="lang.key"
+ :label="lang.key"
```

2022-08-28 22:32 UTC, PickleNik commented
https://vuejs.org/guide/essentials/template-syntax.html#attribute-bindings
You'll notice it highlights differently in the editor when you add a colon `:`

2022-08-29 00:54 UTC, PickleNik approved these changes

2022-08-29 00:54 UTC, merged